apiVersion: v1
kind: Service
metadata:
  name: croc-hunter-load-balancer
  labels:
    app: croc-hunter-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    app: croc-hunter-dotnet